/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DoctorAppointment {
  'id' : bigint,
  'reasonForVisit' : string,
  'mobileNumber' : string,
  'appointmentDate' : string,
  'appointmentTime' : Time,
  'patientName' : string,
  'doctorName' : string,
}
export interface MedicineOrder {
  'id' : bigint,
  'prescriptionFileUrl' : [] | [string],
  'deliveryDate' : string,
  'mobileNumber' : string,
  'deliveryTime' : Time,
  'patientName' : string,
  'fullAddress' : string,
  'deliveryTimingPreference' : string,
}
export interface PathologyBooking {
  'id' : bigint,
  'selectedTests' : Array<string>,
  'date' : string,
  'time' : Time,
  'mobileNumber' : string,
  'sampleCollectionType' : string,
  'patientName' : string,
}
export interface Time { 'hour' : number, 'minute' : number }
export interface UltrasoundBooking {
  'id' : bigint,
  'date' : string,
  'time' : Time,
  'mobileNumber' : string,
  'selectedService' : string,
  'patientName' : string,
}
export interface _SERVICE {
  'getDoctorAppointments' : ActorMethod<[], Array<DoctorAppointment>>,
  'getMedicineOrders' : ActorMethod<[], Array<MedicineOrder>>,
  'getPathologyBookings' : ActorMethod<[], Array<PathologyBooking>>,
  'getUltrasoundBookings' : ActorMethod<[], Array<UltrasoundBooking>>,
  'submitDoctorAppointment' : ActorMethod<
    [string, string, string, string, Time, string],
    bigint
  >,
  'submitMedicineOrder' : ActorMethod<
    [string, string, [] | [string], string, Time, string, string],
    bigint
  >,
  'submitPathologyBooking' : ActorMethod<
    [string, string, Array<string>, string, Time, string],
    bigint
  >,
  'submitUltrasoundBooking' : ActorMethod<
    [string, string, string, string, Time],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];