/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Record({ 'hour' : IDL.Nat8, 'minute' : IDL.Nat8 });
export const DoctorAppointment = IDL.Record({
  'id' : IDL.Nat,
  'reasonForVisit' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'appointmentDate' : IDL.Text,
  'appointmentTime' : Time,
  'patientName' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const MedicineOrder = IDL.Record({
  'id' : IDL.Nat,
  'prescriptionFileUrl' : IDL.Opt(IDL.Text),
  'deliveryDate' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'deliveryTime' : Time,
  'patientName' : IDL.Text,
  'fullAddress' : IDL.Text,
  'deliveryTimingPreference' : IDL.Text,
});
export const PathologyBooking = IDL.Record({
  'id' : IDL.Nat,
  'selectedTests' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'time' : Time,
  'mobileNumber' : IDL.Text,
  'sampleCollectionType' : IDL.Text,
  'patientName' : IDL.Text,
});
export const UltrasoundBooking = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'time' : Time,
  'mobileNumber' : IDL.Text,
  'selectedService' : IDL.Text,
  'patientName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDoctorAppointments' : IDL.Func(
      [],
      [IDL.Vec(DoctorAppointment)],
      ['query'],
    ),
  'getMedicineOrders' : IDL.Func([], [IDL.Vec(MedicineOrder)], ['query']),
  'getPathologyBookings' : IDL.Func([], [IDL.Vec(PathologyBooking)], ['query']),
  'getUltrasoundBookings' : IDL.Func(
      [],
      [IDL.Vec(UltrasoundBooking)],
      ['query'],
    ),
  'submitDoctorAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitMedicineOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitPathologyBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitUltrasoundBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Record({ 'hour' : IDL.Nat8, 'minute' : IDL.Nat8 });
  const DoctorAppointment = IDL.Record({
    'id' : IDL.Nat,
    'reasonForVisit' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'appointmentDate' : IDL.Text,
    'appointmentTime' : Time,
    'patientName' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const MedicineOrder = IDL.Record({
    'id' : IDL.Nat,
    'prescriptionFileUrl' : IDL.Opt(IDL.Text),
    'deliveryDate' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'deliveryTime' : Time,
    'patientName' : IDL.Text,
    'fullAddress' : IDL.Text,
    'deliveryTimingPreference' : IDL.Text,
  });
  const PathologyBooking = IDL.Record({
    'id' : IDL.Nat,
    'selectedTests' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'time' : Time,
    'mobileNumber' : IDL.Text,
    'sampleCollectionType' : IDL.Text,
    'patientName' : IDL.Text,
  });
  const UltrasoundBooking = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'time' : Time,
    'mobileNumber' : IDL.Text,
    'selectedService' : IDL.Text,
    'patientName' : IDL.Text,
  });
  
  return IDL.Service({
    'getDoctorAppointments' : IDL.Func(
        [],
        [IDL.Vec(DoctorAppointment)],
        ['query'],
      ),
    'getMedicineOrders' : IDL.Func([], [IDL.Vec(MedicineOrder)], ['query']),
    'getPathologyBookings' : IDL.Func(
        [],
        [IDL.Vec(PathologyBooking)],
        ['query'],
      ),
    'getUltrasoundBookings' : IDL.Func(
        [],
        [IDL.Vec(UltrasoundBooking)],
        ['query'],
      ),
    'submitDoctorAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitMedicineOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitPathologyBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitUltrasoundBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };